### ISSUE TITLE
Wiki contributions

### ISSUE THREAD

**Issue by almorelle** [nicovuignier/centriphone#7]
Hello,

You actually can't contribute to a wiki on Github via the traditional fork/pull-request thing.

How would you like us to contribute to it? Submit markdown pages to the root of the main repo and you'll add them to the wiki?

For example, I wanted to add feedback on the type of string used, I'm not sure were to post this.

Thank you so much for sharing all this.

**Comment by nicovuignier** [comment]
hey almorelle,

I changed the wiki settings, now anyone should be able to contribute!

thanks!
