### ISSUE TITLE
Redesign for a RaspberryPi?

### ISSUE THREAD

**Issue by AlexFielder** [nicovuignier/centriphone#9]
Personally I love the concept; but I'm not too happy about throwing a £300 device around on a glider- with the source CAD file we could redesign it for use with the £30 RaspberryPi.

Power might be an issue I suppose and the Pi would need a case.

Thoughts?

**Comment by ecols33** [comment]
Seems sort of bulky, whereas cameras and phones are sleek and compact

**Comment by carvehard** [comment]
> Seems sort of bulky, whereas cameras and phones are sleek and compact 

The MacGyver design slips easily into your pocket and is easier to build:
https://github.com/nicovuignier/centriphone/wiki/%22MacGyver%22-ultrasimple-design
